### ISSUE TITLE
Instructions for static linkage of libplinkio

### ISSUE THREAD

**Issue by ofrei** [mfranberg/libplinkio#10]
I would like to link libplinkio statically with my application. Do you have some instructions how to compile libplinkio into a static library? I'm not quite familiar with `./configure` system - it might be an easy task...

**Comment by mfranberg** [comment]
Instead of building it with ./configure, you can build it with cmake, there is a target libplinkio-static that should be what you need.

In the root you can do:
```
mkdir build
cd build
cmake ../
make libplinkio-static
```

This will produce a libplinkio.a in the src folder. (it is probably possible to do it with configure as well, maybe `./configure LDFLAGS="-static"` could work)

**Comment by ofrei** [comment]
Great, thanks a lot! This works for me :)
